const C=window.SITE_CONTENT, app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={arrow:'M5 12h14m-6-6 6 6-6 6',play:'m9 5 11 7-11 7Z',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',music:'M9 18V5l12-2v13M9 8l12-2M9 18a3 3 0 1 1-3-3c1.7 0 3 1.3 3 3Zm12-2a3 3 0 1 1-3-3c1.7 0 3 1.3 3 3Z',check:'m5 12 4 4L19 6',gift:'M3 8h18v4H3zM5 12v9h14v-9M12 8v13M12 8H7a3 3 0 1 1 3-3Zm0 0h5a3 3 0 1 0-3-3Z',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-5',chat:'M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z',menu:'M4 6h16M4 12h16M4 18h16',down:'m6 9 6 6 6-6',headphones:'M3 14v-3a9 9 0 0 1 18 0v3M3 13h4v8H3zm14 0h4v8h-4z'};
const icon=(n,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.music}"/></svg>`;
const cta=(text='Criar minha canção',cls='')=>`<a class="button ${cls}" href="/criar">${text}${icon('arrow')}</a>`;
const brand=()=>`<a class="brand" href="/" aria-label="Minha Canção — início"><span class="logo-window"><img src="/assets/logo.png" alt="Minha Canção" width="700" height="467"></span></a>`;
const photo=(type,cls='',alt='Momentos especiais para guardar')=>`<div class="photo ${type} ${cls}"><img src="/assets/${type}.jpg" alt="${alt}" loading="lazy" width="1254" height="1254"></div>`;
const waves=()=>`<div class="wave" aria-hidden="true">${Array.from({length:46},(_,i)=>`<i style="height:${10+Math.abs(Math.sin(i*2.3)*Math.cos(i*.4))*32}px"></i>`).join('')}</div>`;
function header(simple=false){return `${!simple&&C.stats?.delivered?`<div class="delivery-banner">${icon('music')} <strong>${esc(new Intl.NumberFormat('pt-BR').format(C.stats.delivered))}+ melodias únicas entregues</strong></div>`:''}<header><div class="nav wrap">${brand()}${simple?'<a class="quiet" href="/">Voltar ao site</a>':`<nav id="navigation" aria-label="Principal"><a href="/#como-funciona">Como funciona</a><a href="/#exemplos">Exemplos</a><a href="/#avaliacoes">Avaliações</a><a href="/#duvidas">Dúvidas</a></nav><div class="nav-actions">${cta()}<button class="menu icon-button" aria-label="Abrir menu" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button></div>`}</div></header>`}
const footer=()=>`<footer><div class="wrap footer-grid"><div>${brand()}<p>Suas histórias em música.</p></div><div><a href="/#como-funciona">Como funciona</a><a href="/#duvidas">Perguntas frequentes</a><a href="/contato">Contato</a></div><div><a href="/termos">Termos de uso</a><a href="/privacidade">Política de privacidade</a></div><div>${['Instagram','TikTok','WhatsApp'].map(n=>`<a href="${esc(C[n.toLowerCase()]||'/contato')}">${n}${icon('arrow')}</a>`).join('')}</div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Minha Canção</span><span>Feita de histórias. Feita para sentir.</span></div></footer>`;
function home(){const occasions=[['Aniversário','Mais um ano. Uma nova trilha.','familia'],['Casamento','O sim de vocês, em música.','casal'],['Namoro','Só vocês sabem como começou.','casal'],['Dia das Mães','Todo amor merece um refrão.','familia'],['Dia dos Pais','Para quem sempre esteve aqui.','familia'],['Homenagem','Um jeito de manter por perto.','memorias'],['Pedido de casamento','Uma pergunta inesquecível.','casal'],['Amizade','As melhores histórias são juntos.','memorias'],['Família','O nosso lugar no mundo.','familia'],['Só porque sim','Amor não precisa de data.','casal']];
app.innerHTML=header()+`<main id="main"><section class="hero wrap"><div class="hero-copy"><div class="hero-note">${icon('music')} Uma música feita exclusivamente para quem você ama</div><h1>Transforme <em>sua história</em> em uma canção <em>inesquecível.</em></h1><p>Conte os momentos que marcaram sua história. A gente transforma tudo em uma música que só poderia ser de vocês.</p><div class="benefits"><span>${icon('check')} 100% personalizada</span><span>${icon('check')} A sua história na letra</span><span>${icon('check')} Seu estilo, sua emoção</span><span>${icon('check')} Entrega digital</span></div><div class="hero-action">${cta()}</div><small class="under-cta">Leva poucos minutos para contar sua história.</small></div><div class="hero-art"><div class="photo hero-photo familia"><img src="/assets/familia.jpg" alt="Família reunida, sorrindo ao pôr do sol no Rio de Janeiro" width="1254" height="1254" fetchpriority="high"></div><div class="image-caption">Tem coisas que só uma canção consegue dizer.</div><div class="floating-note">${icon('heart')} Para ouvir. Sentir. Guardar.</div><div class="hero-player"><div class="record-cover">${icon('music')}</div><div class="track"><strong>Nossa Canção</strong><span>Minha Canção · feita para vocês</span>${waves()}<div class="track-time"><span>0:00</span><span>Prévia em breve</span></div></div><button class="round" data-preview aria-label="Ouvir Nossa Canção">${icon('play')}</button></div></div></section>
${C.stats?.songs||C.stats?.satisfaction||C.stats?.expressHours?`<section class="verified-stats wrap" aria-label="Resultados da Minha Canção">${C.stats.songs?`<div><strong>+${esc(new Intl.NumberFormat('pt-BR').format(C.stats.songs))}</strong><span>Canções criadas</span></div>`:''}${C.stats.satisfaction?`<div><strong>${esc(String(C.stats.satisfaction).replace('.',','))}/5</strong><span>Satisfação</span></div>`:''}${C.stats.expressHours?`<div><strong>${esc(C.stats.expressHours)}h</strong><span>Entrega expressa</span></div>`:''}</section>`:''}<div class="promise"><div class="wrap promise-inner"><span>${icon('heart')} Histórias reais transformadas em música.</span><span>${icon('music')} Uma letra que fala de você</span><span>${icon('gift')} Um presente para guardar</span></div></div>
<section class="section wrap" id="ocasioes"><div class="section-head"><h2>Um presente que ninguém espera.<br><em>E ninguém esquece.</em></h2><p>Flores acabam. Chocolates terminam. Mas uma música pode trazer uma história inteira de volta em poucos segundos.</p></div><div class="occasion-grid">${occasions.slice(0,5).map(([n,t,p])=>`<a href="/criar?ocasiao=${encodeURIComponent(n)}" class="occasion">${photo(p,'',n)}<div><h3>${n}</h3><p>${t}</p>${icon('arrow')}</div></a>`).join('')}</div><details class="more-occasions"><summary>Mais motivos para emocionar ${icon('down')}</summary><div class="occasion-grid">${occasions.slice(5).map(([n,t,p])=>`<a href="/criar?ocasiao=${encodeURIComponent(n)}" class="occasion">${photo(p,'',n)}<div><h3>${n}</h3><p>${t}</p>${icon('arrow')}</div></a>`).join('')}</div></details></section>
<section class="how section" id="como-funciona"><div class="wrap"><div class="center"><h2>Você conta a história.<br><em>A gente transforma em música.</em></h2><p>Da primeira lembrança ao primeiro play, em 3 passos.</p></div><div class="steps">${[['chat','Conte sua história','Conte sobre a pessoa, os momentos especiais e aquilo que não pode faltar na música.'],['music','Personalizamos sua canção','Suas respostas viram uma letra e uma composição feitas especialmente para essa história.'],['gift','Receba e emocione','Receba sua canção digital para ouvir, guardar e compartilhar com quem você ama.']].map(([i,t,p],n)=>`<article><div class="step-top">${icon(i)}<span>0${n+1}</span></div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div><div class="center">${cta('Começar minha canção')}<p class="small">Entrega em poucos minutos após a confirmação do pagamento.*</p></div></div></section>
<section class="section examples" id="exemplos"><div class="wrap"><div class="section-head"><h2>Ouça histórias que<br><em>viraram música.</em></h2><p>Cada história tem seu próprio ritmo.<br>Qual vai ser o de vocês?</p></div><div class="tracks">${C.examples.map((e,i)=>`<article class="music-card">${photo(e.image,'',e.occasion)}<div class="music-card-copy"><span class="small">${esc(e.occasion)}</span><h3>${esc(e.title)}</h3><p>${esc(e.genre)}</p><div class="card-player"><button class="round" data-audio="${i}" aria-label="Ouvir ${esc(e.title)}">${icon('play')}</button>${waves()}</div><small>${e.audio?'Ouça uma canção de exemplo':'Áudio de exemplo em breve'}</small></div></article>`).join('')}</div></div></section>
<section class="story-section wrap"><div class="story-photo">${photo('memorias','','Mosaico ilustrativo de casais, familiares, amigos e pessoas ouvindo música')}</div><div class="story-copy"><h2>Histórias reais.<br><em>Emoções reais.</em></h2><p>O abraço de quem está longe. A viagem que virou história. O jeito que só aquela pessoa tem de fazer você rir.</p><p>Cada pessoa tem uma história que merece ser ouvida.</p><a class="text-link" href="/criar">A sua pode ser a próxima ${icon('arrow')}</a><small>Imagens ilustrativas da marca.</small></div></section>
<section class="section wrap compare"><div><h2>Não é só um presente.<br>É a história de vocês<br><em>em música.</em></h2><p>Tem coisas que são difíceis de dizer.<br>Às vezes é mais fácil cantar.</p></div><div class="comparison"><div><h3>Presentes comuns</h3><ul><li>Flores</li><li>Perfume</li><li>Roupa</li><li>Chocolate</li><li>Vale-presente</li></ul></div><div><h3>Minha Canção</h3><ul>${['Feita exclusivamente para a pessoa','Conta uma história real','Pode ser ouvida para sempre','Uma música que só vocês têm','Um presente cheio de significado'].map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul></div></div></section>
<section class="personal section"><div class="wrap personal-grid"><div><h2>Do seu jeito.<br><em>Do primeiro acorde<br>ao último refrão.</em></h2><p>Você escolhe o estilo, a emoção e a voz.<br>A gente cuida de transformar em canção.</p>${cta()}</div><div class="preferences">${[['Estilo musical',['Sertanejo','MPB','Pop','Pagode','Rock','Gospel','Acústico','Outros']],['Clima',['Romântico','Emocionante','Feliz','Inspirador','Nostálgico']],['Voz',['Masculina','Feminina','Surpreenda-me']]].map(([n,vs])=>`<fieldset><legend>${n}</legend><div class="chips">${vs.map(v=>`<button class="chip" data-pref="${n}" aria-pressed="false">${v}</button>`).join('')}</div></fieldset>`).join('')}<p class="small">Experimente suas combinações. Você pode mudar tudo no quiz.</p></div></div></section>
<section class="big-cta"><div class="wrap center">${icon('music')}<h2>Tem uma história que<br><em>merece virar música?</em></h2><p>Conte para a gente. O próximo refrão pode ser sobre vocês.</p>${cta('Criar minha canção','light')}<small>Comece agora. Leva poucos minutos.</small></div></section>
<section class="trust wrap">${[['heart','Feita para você','Nenhuma história é igual à outra.'],['shield','Compra segura','Confira todos os detalhes antes de pagar.'],['headphones','Entrega digital','Sua canção pronta para ouvir e compartilhar.'],['chat','Suporte humano','Um canal para ajudar com a sua história.']].map(([i,t,p])=>`<div>${icon(i)}<h3>${t}</h3><p>${p}</p></div>`).join('')}</section>
<section class="section reviews wrap" id="avaliacoes"><div><h2>É difícil explicar a reação.<br><em>Melhor ouvir de quem viveu.</em></h2><p>Em breve, histórias e reações de quem recebeu uma Minha Canção.</p></div><div class="review-empty">${icon('chat')}<h3>As próximas histórias começam aqui.</h3><p>Este espaço vai receber depoimentos e vídeos de clientes, publicados com autorização.</p><a href="/criar" class="text-link">Conte a sua história ${icon('arrow')}</a></div></section>
<section class="faq section" id="duvidas"><div class="wrap faq-grid"><div><h2>Antes do<br><em>primeiro play.</em></h2><p>A gente responde às suas dúvidas.</p><a class="text-link" href="/contato">Fale com a gente ${icon('arrow')}</a></div><div>${C.faq.map(([q,a])=>`<details><summary>${esc(q)}${icon('down')}</summary><p>${esc(a)}</p></details>`).join('')}</div></div></section>
<section class="final-cta section wrap center"><h2>Uma história como a sua<br><em>só existe uma vez.</em></h2><p>Transforme seus momentos em uma canção<br>que pode ser ouvida para sempre.</p>${cta()}<p class="small">Uma canção personalizada · Entrega digital</p></section><p class="delivery-note wrap">* A entrega em poucos minutos depende da integração de produção automática, em preparação. Os pedidos ainda não estão abertos.</p></main>`+footer();bindCommon();}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
let currentAudio=null;
function bindCommon(){document.querySelector('.menu')?.addEventListener('click',e=>{const b=e.currentTarget;const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',!open);document.querySelector('#navigation').classList.toggle('open',!open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#navigation')?.classList.remove('open');document.querySelector('.menu')?.setAttribute('aria-expanded','false')}));document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>toast('Estamos preparando os áudios de exemplo. Em breve você poderá ouvir por aqui.'));document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{const src=C.examples[+b.dataset.audio].audio;if(!src)return toast('Este exemplo ainda não tem áudio disponível.');if(currentAudio?.button===b&&!currentAudio.audio.paused){currentAudio.audio.pause();b.innerHTML=icon('play');return}if(currentAudio){currentAudio.audio.pause();currentAudio.button.innerHTML=icon('play')}const audio=new Audio(src);currentAudio={audio,button:b};audio.play().then(()=>{b.textContent='Ⅱ'}).catch(()=>toast('Não foi possível carregar o áudio. Tente novamente.'));audio.onended=()=>b.innerHTML=icon('play')});document.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{document.querySelectorAll(`[data-pref="${b.dataset.pref}"]`).forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');const map={'Estilo musical':'style','Clima':'emotion','Voz':'voice'};const names={'Romântico':'Apaixonada','Emocionante':'Emocionada','Inspirador':'Inspirada','Nostálgico':'Nostálgica','Surpreenda-me':'Pode me surpreender','Outros':'Outro'};answers[map[b.dataset.pref]]=names[b.textContent]||b.textContent;save()})}
const questions=[
{key:'who',title:'Para quem é essa canção?',hint:'Pense em quem você quer surpreender.',options:['Meu amor','Minha mãe','Meu pai','Meu filho ou filha','Um amigo ou amiga','Minha família','Outra pessoa']},
{key:'name',title:'Qual é o nome dessa pessoa?',hint:'Pode ser o nome ou aquele apelido que só vocês usam.',type:'text',placeholder:'O nome de alguém especial'},
{key:'occasion',title:'Qual é a ocasião?',options:['Aniversário','Casamento','Aniversário de namoro','Pedido de casamento','Dia das Mães','Dia dos Pais','Homenagem','Só quero surpreender','Outro']},
{key:'met',title:'Como vocês se conheceram?',hint:'Se for alguém da família, conte uma das suas primeiras lembranças.',type:'textarea'},
{key:'memory',title:'Qual momento de vocês você nunca vai esquecer?',hint:'Uma viagem, um abraço, uma conversa. Os pequenos detalhes fazem diferença.',type:'textarea'},
{key:'special',title:'O que torna essa pessoa especial para você?',hint:'Não precisa encontrar palavras perfeitas. Conte do seu jeito.',type:'textarea'},
{key:'details',title:'Quais detalhes precisam aparecer na música?',hint:'Apelidos, lugares, viagens, filhos, datas, manias, frases ou momentos especiais.',type:'textarea'},
{key:'phrase',title:'Existe alguma frase que você quer muito ouvir na música?',hint:'Aquela frase que tem a cara de vocês.',type:'text',optional:true},
{key:'style',title:'Qual estilo combina mais com essa história?',options:['Sertanejo','MPB','Pop','Pagode','Rock','Gospel','Acústico','Outro']},
{key:'emotion',title:'Como você quer que essa música faça a pessoa se sentir?',options:['Emocionada','Apaixonada','Feliz','Nostálgica','Inspirada','Surpreendida']},
{key:'voice',title:'Qual voz você prefere?',options:['Masculina','Feminina','Pode me surpreender']}
];
let answers={},step=-1;try{const draft=JSON.parse(sessionStorage.getItem('mc-draft')||'{}');answers=draft.answers||{};step=Number.isInteger(draft.step)?Math.max(-1,Math.min(11,draft.step)):-1}catch{}
function save(){try{sessionStorage.setItem('mc-draft',JSON.stringify({answers,step}))}catch{}}
function quiz(){const occasion=new URLSearchParams(location.search).get('ocasiao');if(occasion){answers.occasion=({'Namoro':'Aniversário de namoro','Só porque sim':'Só quero surpreender','Amizade':'Outro','Família':'Outro'}[occasion]||occasion);save()}app.innerHTML=header(true)+`<main id="main" class="quiz"><div class="quiz-progress"><div class="wrap"><span>Sua história, em música</span><span id="progress-label"></span></div><div class="progress-track"><i id="progress-fill"></i></div></div><div id="question" class="quiz-content"></div><p class="quiz-foot">Suas respostas ficam nesta sessão do navegador. ${icon('heart')}</p></main>`;renderQuestion()}
function renderQuestion(){requestAnimationFrame(()=>{const title=document.querySelector('#question h1');if(title){title.tabIndex=-1;title.focus({preventScroll:true})}});window.scrollTo({top:0,behavior:'instant'});const target=document.querySelector('#question');document.querySelector('#progress-label').textContent=step<0?'Vamos começar':step===11?'Sua canção':'Pergunta '+(step+1)+' de 11';document.querySelector('#progress-fill').style.width=`${Math.max(0,step+1)/12*100}%`;if(step<0){target.innerHTML=`<div class="intro-note">${icon('music')}</div><h1>Vamos criar uma música<br>que conte <em>essa história.</em></h1><p>Algumas perguntas. As suas melhores lembranças.<br>E uma canção que vai ser só de vocês.</p><button class="button" id="start">Começar ${icon('arrow')}</button><small>Não precisa saber escrever. Só precisa sentir.</small>`;document.querySelector('#start').onclick=()=>{step=0;save();renderQuestion()};return}
if(step===11){target.innerHTML=`${icon('music','summary-icon')}<h1>Já conseguimos imaginar<br><em>a sua canção.</em></h1><p>É aqui que as suas lembranças começam a ganhar melodia.</p><div class="summary-list">${[['Para','name',1],['Ocasião','occasion',2],['Estilo','style',8],['Clima','emotion',9],['Voz','voice',10]].map(([l,k,n])=>`<div><span>${l}</span><strong>${esc(answers[k])}</strong><button class="text-link" data-edit="${n}" aria-label="Editar ${l}">Editar</button></div>`).join('')}</div><div class="quiz-actions"><button class="quiet" id="back">Voltar</button><a class="button" href="/checkout">Criar minha canção ${icon('arrow')}</a></div>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{step=+b.dataset.edit;save();renderQuestion()});document.querySelector('#back').onclick=()=>{step=10;save();renderQuestion()};return}
const q=questions[step];target.innerHTML=`<h1>${q.title}</h1>${q.hint?`<p>${q.hint}</p>`:''}<form id="quiz-form"><div class="answer-area">${q.options?`<div class="option-grid" role="group" aria-label="${q.title}">${q.options.map(v=>`<label class="option"><input type="radio" name="answer" value="${esc(v)}" ${answers[q.key]===v?'checked':''} required><span>${esc(v)}</span>${icon('check')}</label>`).join('')}</div>`:`<label class="sr-only" for="answer">${q.title}</label>${q.type==='textarea'?`<textarea id="answer" name="answer" maxlength="3000" placeholder="Conte aqui, do seu jeito…" required>${esc(answers[q.key])}</textarea>`:`<input id="answer" name="answer" type="text" maxlength="200" placeholder="${q.placeholder||'Escreva a sua frase…'}" value="${esc(answers[q.key])}" ${q.optional?'':'required'} autocomplete="off">`}${q.optional?'<button class="quiet skip-phrase" type="button" id="skip-phrase">Não tenho nenhuma</button>':''}`}</div><p class="form-error" id="form-error" role="alert"></p><div class="quiz-actions"><button type="button" class="quiet" id="back">Voltar</button><button class="button" type="submit">${step===10?'Ver minha canção':'Continuar'}${icon('arrow')}</button></div></form>`;
const form=document.querySelector('#quiz-form');const capture=()=>{const value=new FormData(form).get('answer');if(value!==null){answers[q.key]=String(value);save()}};form.oninput=capture;form.onchange=capture;form.onsubmit=e=>{e.preventDefault();const value=String(new FormData(form).get('answer')||'').trim();if(!value&&q.optional){answers[q.key]='Não tenho nenhuma';step++;save();renderQuestion();return}if(!value){document.querySelector('#form-error').textContent='Conte um pouquinho mais para continuar.';return}answers[q.key]=value;step++;save();renderQuestion()};document.querySelector('#back').onclick=()=>{capture();step--;save();renderQuestion()};document.querySelector('#skip-phrase')?.addEventListener('click',()=>{answers.phrase='Não tenho nenhuma';step++;save();renderQuestion()});}
function checkout(){if(!questions.every(q=>String(answers[q.key]||'').trim())){app.innerHTML=header(true)+`<main id="main" class="section wrap center"><h1>Primeiro, <em>a sua história.</em></h1><p>Complete as perguntas para montar sua canção.</p>${cta('Continuar minha história')}</main>`;return}app.innerHTML=header(true)+`<main id="main" class="section wrap checkout"><div><h1>Sua história está<br><em>quase virando música.</em></h1><p>Confira os detalhes da sua canção.</p><div class="checkout-summary"><h2>Uma canção para ${esc(answers.name)}</h2><p>${esc(answers.occasion)} · ${esc(answers.style)} · ${esc(answers.voice)}</p><details><summary>Rever a história ${icon('down')}</summary>${questions.filter(q=>!q.options).map(q=>`<h3>${esc(q.title)}</h3><p>${esc(answers[q.key])}</p>`).join('')}</details><a class="text-link" href="/criar">Editar minhas respostas</a></div><h2 class="extras-heading">Um toque a mais?</h2><p>Extras opcionais. Você escolhe o que faz sentido.</p><div class="extras">${C.extras.map((e,i)=>`<label><input type="checkbox" data-extra="${i}" ${e.price==null?'disabled':''}><span>${esc(e.name)}</span><small>${e.price==null?'Em breve':money(e.price)}</small></label>`).join('')}</div></div><aside class="order"><h2>Sua Minha Canção</h2><p>Letra e música personalizadas com a sua história.</p><div class="price-line"><span>Canção personalizada</span><strong>${money(C.price)}</strong></div><div id="extra-lines"></div><div class="total"><span>Total</span><strong id="total">${money(C.price)}</strong></div><p class="small">Entrega digital · Previsão: poucos minutos*</p><button class="button" id="pay" disabled>Pedidos em breve</button><p class="small">Estamos preparando o pagamento e a entrega automática. Nenhum valor será cobrado nesta prévia.</p><button class="text-link" id="download">Guardar minha história</button><p class="small">Baixe suas respostas para continuar depois.</p></aside></main>`+footer();document.querySelectorAll('[data-extra]').forEach(i=>i.onchange=()=>{let total=C.price;let rows='';document.querySelectorAll('[data-extra]:checked').forEach(e=>{const x=C.extras[+e.dataset.extra];total+=x.price;rows+=`<div class="price-line"><span>${esc(x.name)}</span><strong>${money(x.price)}</strong></div>`});document.querySelector('#extra-lines').innerHTML=rows;document.querySelector('#total').textContent=money(total)});document.querySelector('#download').onclick=()=>{const blob=new Blob([questions.map(q=>q.title+'\n'+answers[q.key]).join('\n\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='minha-historia.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
const money=n=>n==null?'A definir':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
function info(type){const data={contato:['Vamos conversar.','O canal de atendimento da Minha Canção será divulgado em breve. Enquanto isso, você já pode preparar a sua história no quiz.'],termos:['Termos de uso','Esta é uma prévia da Minha Canção. Não recebemos pagamentos nem confirmamos pedidos nesta versão. As condições de compra, entrega, alterações e uso da canção serão disponibilizadas antes da abertura dos pedidos.'],privacidade:['Sua história merece cuidado.','Nesta prévia, as respostas do quiz ficam apenas na sessão deste navegador. Não são enviadas para um servidor ou usadas para gerar uma canção. O botão “Guardar minha história” cria um arquivo no seu dispositivo. Fontes são carregadas do Google Fonts. A política completa será disponibilizada antes da abertura dos pedidos.']};const [h,p]=data[type];app.innerHTML=header(true)+`<main id="main" class="section wrap legal"><h1>${h}</h1><p>${p}</p>${type==='privacidade'?'<button class="button" id="clear">Apagar minhas respostas</button>':cta()}</main>`+footer();document.querySelector('#clear')?.addEventListener('click',()=>{answers={};step=-1;try{sessionStorage.removeItem('mc-draft')}catch{}toast('Suas respostas foram apagadas desta sessão.')})}
const route=location.pathname.replace(/\/$/,'')||'/';if(route==='/criar')quiz();else if(route==='/checkout')checkout();else if(['contato','termos','privacidade'].includes(route.slice(1)))info(route.slice(1));else home();

function jumpToSection(){if(!location.hash)return;const section=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(section)requestAnimationFrame(()=>requestAnimationFrame(()=>section.scrollIntoView({behavior:'instant',block:'start'})));}
window.addEventListener('load',jumpToSection);window.addEventListener('hashchange',jumpToSection);if(document.readyState==='complete')jumpToSection();
